// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace RevengeSolver
{
	public enum Twists
	{
		R,
		L,
		U,
		D,
		F,
		B,
		r,
		l,
		u,
		d,
		f,
		b,
		R2,
		L2,
		U2,
		D2,
		F2,
		B2,
		r2,
		l2,
		u2,
		d2,
		f2,
		b2,
		R_,
		L_,
		U_,
		D_,
		F_,
		B_,
		r_,
		l_,
		u_,
		d_,
		f_,
		b_
	}

	public class Twist{

		public static Twist R = new Twist(new Edge[][]{new Edge[]{Edge.UF, Edge.UF}});

		


		private readonly Edge[][] _edgeCycles;

		private Twist(Edge[][] edgeCycles){
			
		}

		private Twist(Twist twist, int num){
			_edgeCycles = twist._edgeCycles;
		}

	}

}

